project:
  type: website
  output-dir: docs
resources:
  - Grassland1.jpg
  - googlee51ecdb4fdd95756.html 
  
website:
  title: "Md Faizul Kabir"
  site-url: https://faizul-kabir9.github.io/      
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: education.qmd
        text: Education
      - href: presentations.qmd
        text: Conferences and Workshops
      - href: cv.qmd
        text: Curriculum Vitae
    right:
      - icon: envelope
        href: mailto:mkabir9@huskers.unl.edu
      - icon: github
        href: https://github.com/Faizul-Kabir9/
      - icon: linkedin
        href: https://www.linkedin.com/in/faizul-kabir-5b4a6a53/
  page-footer:
    center: "© 2026 Md Faizul Kabir · Built with R"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false
    link-external-newwindow: true
    include-after-body: cover.html

